version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: loan-engine-swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./docs:/usr/share/nginx/html/docs
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/docs/swagger.yaml
    restart: always
